name: Python CI

# Kích hoạt khi push lên main
on:
  push:
    branches: ["main"]

jobs:
  test_api:
    runs-on: ubuntu-latest #Máy ảo ubuntu

    steps:
      - name: Lấy mã nguồn
        uses: actions/checkout@v3

      - name: Cái đặt môi trường python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Thêm các thư viện cần thiết
        run: |
          cd labs
          pip install -r requirements.txt

      - name: Chạy thử test
        run: |
          cd labs
          python -m pytest tests/
  build_docker:
    needs: [test_api] 
    runs-on: ubuntu-latest

    steps:
      - name: Lấy mã nguồn
        uses: actions/checkout@v3

      - name: Đăng nhập vào Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build và Push Docker Image
        run: |
          cd labs

          docker build -t ${{ secrets.DOCKER_USERNAME }}/mini-api:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/mini-api:latest

      - name: Kích hoạt Render Deploy
        run: curl -X GET "${{ secrets.RENDER_DEPLOY_HOOK }}"
